//! 当前会用到的物块，按公开类型 id 注册。
//!
//! 与模组走同一个 [`ContentModule`]。这里只登记本客户端已经实现交互的类型，
//! 不是从安装目录导出的全表。贴图文件号与类型 id 相同，运行时再打开 `Tiles_{id}.xnb`。

use tr_core::{ContentModule, ContentRegistry, ItemId};

/// 随客户端发布的物块登记。
pub struct VanillaTiles;

impl ContentModule for VanillaTiles {
    fn name(&self) -> &str {
        "vanilla_tiles"
    }

    fn register(&self, registry: &mut ContentRegistry) -> Result<(), String> {
        registry
            .tile(0)
            .key("terraria:dirt")
            .name("泥土")
            .solid(true)
            .merge_dirt(true)
            .max_hp(50)
            .drop(ItemId::DIRT)
            .register()?;
        registry
            .tile(1)
            .key("terraria:stone")
            .name("石头")
            .solid(true)
            .merge_dirt(true)
            .max_hp(100)
            .drop(ItemId::STONE)
            .register()?;
        registry
            .tile(2)
            .key("terraria:grass")
            .name("草")
            .solid(true)
            .merge_dirt(true)
            .max_hp(50)
            .drop(ItemId::DIRT)
            .register()?;
        registry
            .tile(4)
            .key("terraria:torch")
            .name("火把")
            .frame_important(true)
            .replaceable(true)
            .light_radius(8)
            .max_hp(10)
            .drop(ItemId::TORCH)
            .register()?;
        registry
            .tile(5)
            .key("terraria:trees")
            .name("树")
            .tree(true)
            .frame_important(true)
            .max_hp(60)
            .drop(ItemId::WOOD)
            .register()?;
        registry
            .tile(6)
            .key("terraria:iron")
            .name("铁矿")
            .solid(true)
            .merge_dirt(true)
            .max_hp(150)
            .mine_power(35)
            .drop(ItemId::IRON_ORE)
            .register()?;
        registry
            .tile(7)
            .key("terraria:copper")
            .name("铜矿")
            .solid(true)
            .merge_dirt(true)
            .max_hp(80)
            .mine_power(20)
            .drop(ItemId::COPPER_ORE)
            .register()?;
        registry
            .tile(17)
            .key("terraria:furnace")
            .name("熔炉")
            .solid(true)
            .frame_important(true)
            .light_radius(5)
            .max_hp(100)
            .drop(ItemId::FURNACE)
            .register()?;
        registry
            .tile(18)
            .key("terraria:workbench")
            .name("工作台")
            .solid(true)
            .frame_important(true)
            .max_hp(100)
            .drop(ItemId::WORKBENCH)
            .register()?;
        registry
            .tile(19)
            .key("terraria:platform")
            .name("木平台")
            .solid_top(true)
            .frame_important(true)
            .max_hp(40)
            .drop(ItemId::PLATFORM)
            .register()?;
        registry
            .tile(20)
            .key("terraria:sapling")
            .name("树苗")
            .frame_important(true)
            .replaceable(true)
            .max_hp(10)
            .drop(ItemId::SAPLING)
            .register()?;
        registry
            .tile(21)
            .key("terraria:chest")
            .name("木箱")
            .solid(true)
            .frame_important(true)
            .max_hp(60)
            .drop(ItemId::CHEST)
            .register()?;
        registry
            .tile(30)
            .key("terraria:wood")
            .name("木材")
            .solid(true)
            .max_hp(60)
            .drop(ItemId::WOOD)
            .register()?;
        registry
            .tile(53)
            .key("terraria:sand")
            .name("沙子")
            .solid(true)
            .merge_dirt(true)
            .max_hp(50)
            .drop(ItemId::SAND)
            .register()?;
        registry
            .tile(79)
            .key("terraria:bed")
            .name("床")
            .solid(true)
            .frame_important(true)
            .max_hp(40)
            .drop(ItemId::BED)
            .register()?;
        registry
            .tile(147)
            .key("terraria:snow")
            .name("雪块")
            .solid(true)
            .merge_dirt(true)
            .max_hp(50)
            .drop(ItemId::SNOW)
            .register()?;
        registry
            .tile(192)
            .key("terraria:leaf")
            .name("树叶")
            .replaceable(true)
            .max_hp(20)
            .tiles_file(Some(192))
            .register()?;
        registry
            .tile(213)
            .key("terraria:rope")
            .name("绳索")
            .ladder(true)
            .frame_important(true)
            .replaceable(true)
            .max_hp(10)
            .drop(ItemId::ROPE)
            .register()?;
        // 正版没有独立木梯 Tile。本重写暂用本地编号 1000，贴图复用绳索图集。
        registry
            .tile(1000)
            .key("terraria:ladder")
            .name("木梯")
            .ladder(true)
            .frame_important(true)
            .replaceable(true)
            .max_hp(10)
            .drop(ItemId::LADDER)
            .tiles_file(Some(213))
            .register()?;
        Ok(())
    }
}
