//! 配方：徒手 / 工作台 / 熔炉。

use tr_core::ItemId;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CraftStation {
    Hand,
    Workbench,
    Furnace,
}

#[derive(Debug, Clone, Copy)]
pub struct Recipe {
    pub id: &'static str,
    pub station: CraftStation,
    pub inputs: &'static [(ItemId, u32)],
    pub output: ItemId,
    pub output_count: u32,
    pub label: &'static str,
}

pub const RECIPES: &[Recipe] = &[
    Recipe {
        id: "workbench",
        station: CraftStation::Hand,
        inputs: &[(ItemId::WOOD, 10)],
        output: ItemId::WORKBENCH,
        output_count: 1,
        label: "工作台 ×1",
    },
    Recipe {
        id: "wood_pick",
        station: CraftStation::Workbench,
        inputs: &[(ItemId::WOOD, 10)],
        output: ItemId::WOOD_PICK,
        output_count: 1,
        label: "木镐 ×1",
    },
    Recipe {
        id: "stone_pick",
        station: CraftStation::Workbench,
        inputs: &[(ItemId::WOOD, 4), (ItemId::STONE, 10)],
        output: ItemId::STONE_PICK,
        output_count: 1,
        label: "石镐 ×1",
    },
    Recipe {
        id: "wood_hammer",
        station: CraftStation::Workbench,
        inputs: &[(ItemId::WOOD, 6)],
        output: ItemId::WOOD_HAMMER,
        output_count: 1,
        label: "木锤 ×1",
    },
    Recipe {
        id: "wood_sword",
        station: CraftStation::Workbench,
        inputs: &[(ItemId::WOOD, 6)],
        output: ItemId::WOOD_SWORD,
        output_count: 1,
        label: "木剑 ×1",
    },
    Recipe {
        id: "platform",
        station: CraftStation::Hand,
        inputs: &[(ItemId::WOOD, 2)],
        output: ItemId::PLATFORM,
        output_count: 2,
        label: "木平台 ×2",
    },
    Recipe {
        id: "wood_wall",
        station: CraftStation::Workbench,
        inputs: &[(ItemId::WOOD, 1)],
        output: ItemId::WOOD_WALL,
        output_count: 4,
        label: "木墙 ×4",
    },
    Recipe {
        id: "stone_wall",
        station: CraftStation::Workbench,
        inputs: &[(ItemId::STONE, 1)],
        output: ItemId::STONE_WALL,
        output_count: 4,
        label: "石墙 ×4",
    },
    Recipe {
        id: "chest",
        station: CraftStation::Workbench,
        inputs: &[(ItemId::WOOD, 8)],
        output: ItemId::CHEST,
        output_count: 1,
        label: "木箱 ×1",
    },
    Recipe {
        id: "torch",
        station: CraftStation::Hand,
        inputs: &[(ItemId::WOOD, 1), (ItemId::GEL, 1)],
        output: ItemId::TORCH,
        output_count: 3,
        label: "火把 ×3",
    },
    Recipe {
        id: "ladder",
        station: CraftStation::Hand,
        inputs: &[(ItemId::WOOD, 2)],
        output: ItemId::LADDER,
        output_count: 4,
        label: "木梯 ×4",
    },
    Recipe {
        id: "rope",
        station: CraftStation::Hand,
        inputs: &[(ItemId::WOOD, 1)],
        output: ItemId::ROPE,
        output_count: 8,
        label: "绳索 ×8",
    },
    Recipe {
        id: "wood_armor",
        station: CraftStation::Workbench,
        inputs: &[(ItemId::WOOD, 12), (ItemId::GEL, 4)],
        output: ItemId::WOOD_ARMOR,
        output_count: 1,
        label: "木甲 ×1",
    },
    Recipe {
        id: "wood_bow",
        station: CraftStation::Workbench,
        inputs: &[(ItemId::WOOD, 8), (ItemId::STONE, 2)],
        output: ItemId::WOOD_BOW,
        output_count: 1,
        label: "木弓 ×1",
    },
    Recipe {
        id: "wood_arrow",
        station: CraftStation::Hand,
        inputs: &[(ItemId::WOOD, 1)],
        output: ItemId::WOOD_ARROW,
        output_count: 5,
        label: "木箭 ×5",
    },
    Recipe {
        id: "gel_staff",
        station: CraftStation::Workbench,
        inputs: &[(ItemId::WOOD, 4), (ItemId::GEL, 6), (ItemId::STONE, 2)],
        output: ItemId::GEL_STAFF,
        output_count: 1,
        label: "凝胶法杖 ×1",
    },
    Recipe {
        id: "furnace",
        station: CraftStation::Workbench,
        inputs: &[(ItemId::STONE, 12), (ItemId::STONE, 4)],
        output: ItemId::FURNACE,
        output_count: 1,
        label: "熔炉 ×1",
    },
    Recipe {
        id: "bed",
        station: CraftStation::Workbench,
        inputs: &[(ItemId::WOOD, 10), (ItemId::GEL, 2)],
        output: ItemId::BED,
        output_count: 1,
        label: "床 ×1",
    },
    Recipe {
        id: "smelt_copper",
        station: CraftStation::Furnace,
        inputs: &[(ItemId::COPPER_ORE, 3)],
        output: ItemId::COPPER_BAR,
        output_count: 1,
        label: "铜锭 ×1",
    },
    Recipe {
        id: "smelt_iron",
        station: CraftStation::Furnace,
        inputs: &[(ItemId::IRON_ORE, 3)],
        output: ItemId::IRON_BAR,
        output_count: 1,
        label: "铁锭 ×1",
    },
    Recipe {
        id: "copper_pick",
        station: CraftStation::Workbench,
        inputs: &[(ItemId::COPPER_BAR, 6), (ItemId::WOOD, 4)],
        output: ItemId::COPPER_PICK,
        output_count: 1,
        label: "铜镐 ×1",
    },
    Recipe {
        id: "cloth_bag",
        station: CraftStation::Hand,
        inputs: &[(ItemId::WOOD, 4), (ItemId::GEL, 2)],
        output: ItemId::CLOTH_BAG,
        output_count: 1,
        label: "布袋 ×1",
    },
    Recipe {
        id: "travel_pack",
        station: CraftStation::Workbench,
        inputs: &[(ItemId::WOOD, 10), (ItemId::GEL, 4), (ItemId::STONE, 2)],
        output: ItemId::TRAVEL_PACK,
        output_count: 1,
        label: "旅行包 ×1",
    },
    Recipe {
        id: "grapple",
        station: CraftStation::Workbench,
        inputs: &[(ItemId::WOOD, 6), (ItemId::STONE, 4)],
        output: ItemId::GRAPPLE,
        output_count: 1,
        label: "钩爪 ×1",
    },
    Recipe {
        id: "cloud_bottle",
        station: CraftStation::Workbench,
        inputs: &[(ItemId::GEL, 6), (ItemId::STONE, 2)],
        output: ItemId::CLOUD_BOTTLE,
        output_count: 1,
        label: "凝胶云瓶 ×1",
    },
];
